TRAIN_DATA = [
    # Client entertainment
    ("Business lunch with clients at Zuma", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Dinner meeting with potential client at Atlantis restaurant", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Coffee meeting with client at Starbucks in Dubai Mall", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Client lunch meeting at Pierchic restaurant", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Corporate hospitality tickets for client at Dubai World Cup", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Paid for client dinner during contract negotiation", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Hosted client at business networking brunch at JBR", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Purchased gift hamper for key client during Ramadan", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Client entertainment expenses at Burj Khalifa lounge", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Corporate box tickets for client at football match", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Paid for team and client desert safari hospitality event", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Client dinner during GITEX networking event", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Bought appreciation gifts for long-term corporate client", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Business breakfast meeting with client at hotel restaurant", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Hosted VIP client at yacht networking event", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Client hospitality expenses at trade show exhibition", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Paid for client afternoon tea meeting at luxury hotel", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Corporate entertainment expenses for visiting overseas client", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Client networking dinner hosted at DIFC restaurant", {"cats": {"client_entertainment": 1, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),



    # Rent and utilities
    ("Monthly office rent for JLT office", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("DEWA bill for October", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Paid rent for Al Barsha warehouse", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Annual office rent payment for Business Bay headquarters", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Paid electricity bill for Sharjah branch", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Water utility payment for warehouse facility", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Internet and office WiFi subscription for main office", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Quarterly cooling and chiller service charges", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Gas bill payment for company kitchen", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Paid Ejari renewal fees for office lease", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Monthly rent for Abu Dhabi satellite office", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Building service and maintenance charges for office tower", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Trash collection and waste management fees for warehouse", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Security service charges included in office utilities", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Parking space rental for company vehicles at office building", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Shared coworking space monthly membership fee", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Office landline and telecom bill payment", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Municipality service fee related to commercial office space", {"cats": {"client_entertainment": 0, "rent_and_utilities": 1, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 0}}),


    # Fines_and_penalties
    ("Traffic fine on Sheikh Zayed Road", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Late trade license renewal penalty", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Dubai Municipality fine for improper waste disposal", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Salik toll violation fine for company vehicle", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Late VAT filing penalty from FTA", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Penalty for delayed corporate tax registration", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("RTA fine for expired vehicle registration", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Labour law fine for delayed salary payment", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Penalty for not renewing employee labour card on time", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("DED fine for operating with expired commercial license", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Civil defense fine for missing fire safety compliance", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Penalty for late submission of ESR notification", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Municipality fine for unauthorized signage installation", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Fine for parking violation by company delivery vehicle", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("FTA penalty for incorrect VAT return submission", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Fine for late renewal of company establishment card", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Penalty for failing to maintain proper accounting records", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Health authority fine for expired employee health cards", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),
    ("Free zone authority penalty for late license renewal", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 0, "fines_and_penalties": 1}}),


    # Salaries and Visas
    ("Visa renewal fees for staff", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Monthly salary payment for software development team", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("End of service gratuity payment for departing employee", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Work permit issuance fees for new hire", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Employment visa processing charges for marketing manager", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Medical fitness test fees for employee visa", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Emirates ID application fee for staff member", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Air ticket allowance payout for employee annual leave", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Overtime salary payment for operations team", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Commission payout to sales staff", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Payroll processing fees for company employees", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Labour card renewal charges for warehouse workers", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Salary advance issued to administrative assistant", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Recruitment agency fees for hiring new engineer", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("Dependent visa sponsorship fees for employee family", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),
    ("WPS salary transfer charges for monthly payroll", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 1, "marketing_and_ads": 0, "fines_and_penalties": 0}}),

    # Marketing and ads
    ("Amount spent on google ads", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Facebook and Instagram advertising campaign costs", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("LinkedIn sponsored posts for B2B marketing", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("SEO agency monthly retainer fee", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Paid influencer promotion on Instagram for product launch", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Billboard advertisement rental on Sheikh Zayed Road", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Printing brochures and promotional flyers", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Email marketing software subscription", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Trade show booth rental at Dubai exhibition center", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Company website redesign and branding costs", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("YouTube video advertisement campaign expenses", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Professional photography for marketing materials", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Content creation and copywriting services for ads", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Promotional merchandise printing with company logo", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("TikTok advertising campaign for brand awareness", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Radio advertisement placement on local UAE station", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Google display network banner advertisement costs", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("PR agency fee for media and press coverage", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}}),
    ("Event sponsorship fee for local business networking event", {"cats": {"client_entertainment": 0, "rent_and_utilities": 0, "salaries_and_visas": 0, "marketing_and_ads": 1, "fines_and_penalties": 0}})

] 