"""increase hashed_pass column size

Revision ID: 11a12abdc5e1
Revises: cbd16a1a7efa
Create Date: 2026-03-16 03:40:09.581163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a12abdc5e1'
down_revision: Union[str, Sequence[str], None] = 'cbd16a1a7efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('incomes', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomes', 'description',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
