"""recreate users table, add new table, update exsisting table columns

Revision ID: cbd16a1a7efa
Revises: 7a5a5bf79aa8
Create Date: 2026-03-13 06:25:25.576723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbd16a1a7efa'
down_revision: Union[str, Sequence[str], None] = '7a5a5bf79aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_unique_constraint('uq_document_text', 'document_knowledge', ['document_name', 'text'])

    # Clear expenses before adding non nullable columns
    op.execute("DELETE FROM expenses")
    op.add_column('expenses', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('expenses', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('expenses', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('expenses', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('expenses_user_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'users', ['created_by'], ['id'])
    op.drop_column('expenses', 'user_id')

    # Clear incomes BEFORE adding non-nullable columns
    op.execute("DELETE FROM incomes")
    op.add_column('incomes', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('incomes', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('incomes', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('incomes', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('incomes_user_id_fkey'), 'incomes', type_='foreignkey')
    op.create_foreign_key(None, 'incomes', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'incomes', 'users', ['created_by'], ['id'])
    op.drop_column('incomes', 'user_id')

    # Clear users BEFORE adding non-nullable columns
    op.execute("DELETE FROM users")
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=False))

    # Create enum type then add column
    role_enum = sa.Enum('admin', 'manager', 'employee', name='roleenum')
    role_enum.create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'manager', 'employee', name='roleenum'), nullable=False))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.drop_column('users', 'company_id')
    op.add_column('incomes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.create_foreign_key(op.f('incomes_user_id_fkey'), 'incomes', 'users', ['user_id'], ['id'])
    op.alter_column('incomes', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('incomes', 'is_approved')
    op.drop_column('incomes', 'company_id')
    op.drop_column('incomes', 'created_by')
    op.add_column('expenses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    # Drop enum type on downgrade
    sa.Enum(name='roleenum').drop(op.get_bind())
    op.create_foreign_key(op.f('expenses_user_id_fkey'), 'expenses', 'users', ['user_id'], ['id'])
    op.alter_column('expenses', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('expenses', 'is_approved')
    op.drop_column('expenses', 'company_id')
    op.drop_column('expenses', 'created_by')
    op.drop_constraint('uq_document_text', 'document_knowledge', type_='unique')
    op.drop_table('companies')
    # ### end Alembic commands ###
